<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FiaPaymentRecordsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $paymentRecords = [
            [
                'member_id' => 'PRM2',
                'member_name' => 'Emmanuel Elioth Lulandala',
                'gawio_la_fia' => 195851.65,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 195851.65,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 195851.65,
            ],
            [
                'member_id' => 'FND1',
                'member_name' => 'Mary Mwinuka',
                'gawio_la_fia' => 45000.00,
                'fia_iliyokomaa' => 1000000.00,
                'jumla' => 1045000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 45000.00,
                'kiasi_baki' => 1000000.00,
            ],
            [
                'member_id' => 'PRM1',
                'member_name' => 'Kanti Ambrose Kimario',
                'gawio_la_fia' => 90000.00,
                'fia_iliyokomaa' => 2000000.00,
                'jumla' => 2090000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 2090000.00,
            ],
            [
                'member_id' => 'ORD7',
                'member_name' => 'Kulwa Mwita Mang\'ana',
                'gawio_la_fia' => 95000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 95000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 95000.00,
                'kiasi_baki' => 0.00,
            ],
            [
                'member_id' => 'ORD10',
                'member_name' => 'Arkelaus Kailembo',
                'gawio_la_fia' => 55000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 55000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 55000.00,
            ],
            [
                'member_id' => 'PRM4',
                'member_name' => 'Living Christopher koka',
                'gawio_la_fia' => 110000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 110000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 110000.00,
            ],
            [
                'member_id' => 'ORD2',
                'member_name' => 'Christina Maeda',
                'gawio_la_fia' => 45000.00,
                'fia_iliyokomaa' => 1000000.00,
                'jumla' => 1045000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 1045000.00,
            ],
            [
                'member_id' => 'ORD5',
                'member_name' => 'Victoria S.Mwambungu',
                'gawio_la_fia' => 125000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 125000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 125000.00,
            ],
            [
                'member_id' => 'PRM5',
                'member_name' => 'Erick Buberwa',
                'gawio_la_fia' => 55000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 55000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 55000.00,
            ],
            [
                'member_id' => 'ASC9',
                'member_name' => 'Erick Anselim Minde',
                'gawio_la_fia' => 55000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 55000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 55000.00,
            ],
            [
                'member_id' => 'ASC13',
                'member_name' => 'Winnrose Elifuraha Mmari',
                'gawio_la_fia' => 55000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 55000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 55000.00,
            ],
            [
                'member_id' => 'ASC1',
                'member_name' => 'Albert Sylvester Nkuhi',
                'gawio_la_fia' => 55000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 55000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 55000.00,
            ],
            [
                'member_id' => 'ASC12',
                'member_name' => 'Aurelia Issack',
                'gawio_la_fia' => 115000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 115000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 115000.00,
            ],
            [
                'member_id' => 'ASC11',
                'member_name' => 'Hamisi Amiri Hasani',
                'gawio_la_fia' => 55000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 55000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 55000.00,
            ],
            [
                'member_id' => 'SCH2',
                'member_name' => 'Sigfred A Ngereza',
                'gawio_la_fia' => 6888.89,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 6888.89,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 6888.89,
            ],
            [
                'member_id' => 'SCH10',
                'member_name' => 'Mwamini Osward Bavuma',
                'gawio_la_fia' => 8600.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 8600.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 8600.00,
            ],
            [
                'member_id' => 'ASC75',
                'member_name' => 'Caroline Ceasar Shija',
                'gawio_la_fia' => 40000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 40000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 40000.00,
                'loan' => 0.00,
                'kiasi_baki' => 0.00,
            ],
            [
                'member_id' => 'SCH7',
                'member_name' => 'Eufomia Pancras Mshanga',
                'gawio_la_fia' => 9300.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 9300.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 9300.00,
            ],
            [
                'member_id' => 'ASC90',
                'member_name' => 'Anno Massawe',
                'gawio_la_fia' => 1458333.33,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 1458333.33,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 1458333.33,
            ],
            [
                'member_id' => 'FND7',
                'member_name' => 'JAPHET METHUSELA MGEMA',
                'gawio_la_fia' => 66703.30,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 66703.30,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 66703.30,
            ],
            [
                'member_id' => 'ASC122',
                'member_name' => 'Josephine Kiwelu',
                'gawio_la_fia' => 129000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 129000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 129000.00,
            ],
            [
                'member_id' => 'ASC119',
                'member_name' => 'ROBERT KIWIA',
                'gawio_la_fia' => 129000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 129000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 129000.00,
            ],
            [
                'member_id' => 'ASC107',
                'member_name' => 'Apolinari Elias Herman',
                'gawio_la_fia' => 10851.65,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 10851.65,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 10851.65,
            ],
            [
                'member_id' => 'SCH58',
                'member_name' => 'Neema Emmanuel Mria',
                'gawio_la_fia' => 5000.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 5000.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 5000.00,
            ],
            [
                'member_id' => 'FND2',
                'member_name' => 'Caesar Maulaga',
                'gawio_la_fia' => 24703.91,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 24703.91,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 24703.91,
                'loan' => 0.00,
                'kiasi_baki' => 0.00,
            ],
            [
                'member_id' => 'SCH69',
                'member_name' => 'Vicent Simon Gabriel',
                'gawio_la_fia' => 1750.00,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 1750.00,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 1750.00,
            ],
            [
                'member_id' => 'ASC93',
                'member_name' => 'Lulu Ilomo',
                'gawio_la_fia' => 1510.99,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 1510.99,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 1510.99,
            ],
            [
                'member_id' => 'ASC131',
                'member_name' => 'Petro Ngalu',
                'gawio_la_fia' => 2962.76,
                'fia_iliyokomaa' => 0.00,
                'jumla' => 2962.76,
                'malipo_ya_vipande_yaliyokuwa_yamepelea' => 0.00,
                'loan' => 0.00,
                'kiasi_baki' => 2962.76,
            ],
        ];

        // Insert records with timestamps
        foreach ($paymentRecords as $record) {
            DB::table('fia_payment_records')->insert([
                ...$record,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('FIA payment records seeded successfully!');
    }
}
